/*
 * generated by Xtext 2.33.0
 */
package org.eclipse.gemoc.gexpressions.xtext.ide


/**
 * Use this class to register ide components.
 */
class GExpressionsIdeModule extends AbstractGExpressionsIdeModule {
}
