/*
 * generated by Xtext 2.33.0
 */
package org.eclipse.gemoc.gexpressions.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.gemoc.gexpressions.xtext.parser.antlr.internal.InternalGExpressionsParser;
import org.eclipse.gemoc.gexpressions.xtext.services.GExpressionsGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class GExpressionsParser extends AbstractAntlrParser {

	@Inject
	private GExpressionsGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGExpressionsParser createParser(XtextTokenStream stream) {
		return new InternalGExpressionsParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "GProgram";
	}

	public GExpressionsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GExpressionsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
