/*
 * generated by Xtext 2.33.0
 */
package org.eclipse.gemoc.gexpressions.xtext.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class GExpressionsUiModule extends AbstractGExpressionsUiModule {
}
