/*
 * generated by Xtext 2.33.0
 */
package org.eclipse.gemoc.gexpressions.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class GExpressionsStandaloneSetup extends GExpressionsStandaloneSetupGenerated {

	def static void doSetup() {
		new GExpressionsStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
