/*
 * generated by Xtext 2.33.0
 */
package org.eclipse.gemoc.gexpressions.xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class GExpressionsRuntimeModule extends AbstractGExpressionsRuntimeModule {
}
